Bugfix: nextcloud-upload

diff --git a/scripts/nextcloud-upload b/scripts/nextcloud-upload
--- a/scripts/nextcloud-upload
+++ b/scripts/nextcloud-upload
@@ -43,7 +43,7 @@ function encode_path
 }
 
 
-if [[ "$#" -lt 2 ]]
+if [[ "$#" -lt 2 || ! -e "$1" ]]
 then
 	error "Usage: $(basename "$0") <DIR> <URL>" \
 	      "" \
@@ -62,6 +62,29 @@ curl -s -f -X PROPFIND "$URL/" >/dev/null \
 
 trap cleanup EXIT
 tmp=$(mktemp)
+
+if [[ -d "$DIR" ]]
+then
+	full="/"
+	encode_path "$DIR" > "$tmp"
+	while IFS= read -r -d '/' dir
+	do
+		full+="$dir/"
+		echo -n "[    ] $full "
+
+		if ! curl -s -f -X MKCOL "$URL/$full" >/dev/null \
+		&& ! curl -s -f -X PROPFIND "$URL/$full" >/dev/null
+		then
+			echo -e "\r[\e[41mFAIL\e[0m]"
+			error "" "Error: Could not create start directory $DIR!"
+		fi
+
+		echo -n -e "\r[\e[32m OK \e[0m]"
+		echo " $full "
+	done < "$tmp"
+	unset full
+	unset dir
+fi
 
 find "$DIR" -xdev \( -type d -o -type f \) -print0 > "$tmp"
 
